name: 01 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:


# Otorgamos los permisos globalmente
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

  #Análisis de dependencias
  sca:
    needs: build
    name: SCA
    uses: ./.github/workflows/sca.yml
    secrets: inherit

  #Análisis de código Estático
  sast:
    needs: build
    name: SAST
    uses: ./.github/workflows/sast.yml
    secrets: inherit

  #Análisis y Uso de Licencias.
  license-compliance:
    needs: build
    name: License Compliance
    uses: ./.github/workflows/license-compliance.yml
    secrets: inherit

  #Cración de Docker
  docker:
    needs: build
    name: Build docker image
    uses: ./.github/workflows/docker.yml
    secrets: inherit
  
