name: 04 SAST

on:
  workflow_dispatch:
  workflow_call:

jobs:
  SAST-CodeQL:
    name: Build and SAST CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ "java" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -B -Dmaven.test.skip

      - name: Cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-target

      - name: Cache m2
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ~/.m2/**/*.jar
          key: ${{ runner.os }}-m2

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: ${{ github.workspace }}/target

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{ matrix.language }}"

      - name: Docker Cleanup and Run
        run: |
          docker rm demoApp || true
          docker run -d -p 8080:8080 --name demoApp myapp-image
        # Asegúrate de reemplazar 'myapp-image' con el nombre correcto de la imagen

  spotbugs:
    name: SAST SpotBugs
    needs: [SAST-CodeQL]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Spotbugs action
        uses: jmservera/spotbugs-github-action@v0.1.0-alpha
        with:
          packages: com.example.-
          target: ./target
          dependenciesPath: ~/.m2
          basePath: src/main/java

      - name: Upload Spotbugs report
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-sarif
          path: ${{github.workspace}}/results.sarif

      - name: Upload Analysis Results
        if: always()
        uses: github/codeql-action/upload-sarif@v2.1.28
        with:
          sarif_file: ${{github.workspace}}/results.sarif







        

